export const enum DI {
    AccountApi = 'AccountApi',
    BackendApi = 'BackendApi',
    BookApi = 'BookApi',
    BrowserHistory = 'BrowserHistory',
    ContributionApi = 'ContributionApi',
    DiscussApi = 'DiscussApi',
    Glaemscribe = 'Glaemscribe',
    GlossApi = 'GlossApi',
    InflectionApi = 'InflectionApi',
    LanguageApi = 'LanguageApi',
    LogApi = 'LogApi',
    RoleManager = 'RoleManager',
    SpeechApi = 'SpeechApi',
    SubscriptionApi = 'SubscriptionApi',
    UtilityApi = 'UtilityApi',
    WordFinderApi = 'WordFinderApi',

    GlobalEvents = 'GlobalEvents',
}
