export const enum DI {
    AccountApi = 'AccountApi',
    BackendApi = 'BackendApi',
    BookApi = 'BookApi',
    BrowserHistory = 'BrowserHistory',
    ContributionApi = 'ContributionApi',
    DiscussApi = 'DiscussApi',
    Glaemscribe = 'Glaemscribe',
    GlossApi = 'GlossApi',
    InflectionApi = 'InflectionApi',
    LanguageApi = 'LanguageApi',
    LogApi = 'LogApi',
    PasskeyApi = 'PasskeyApi',
    RoleManager = 'RoleManager',
    SentenceApi = 'SentenceApi',
    SpeechApi = 'SpeechApi',
    SubscriptionApi = 'SubscriptionApi',
    UtilityApi = 'UtilityApi',
    CrosswordApi = 'CrosswordApi',
    WordFinderApi = 'WordFinderApi',
    WordListApi = 'WordListApi',

    GlobalEvents = 'GlobalEvents',
}
