<?php

namespace Tests\Unit\Repositories;

use Tests\TestCase;

use Auth;
use DB;
use Queue;

use Tests\Unit\Traits\{
    CanCreateGloss
};

use App\Repositories\DiscussRepository;
use App\Repositories\ValueObjects\ForumThreadForEntityValue;
use App\Models\{
    Account,
    ForumDiscussion,
    ForumGroup,
    ForumPost,
    ForumPostLike,
    ForumThread
};
use Illuminate\Foundation\Testing\DatabaseTransactions;

class DiscussRepositoryTest extends TestCase
{
    use DatabaseTransactions;

    use CanCreateGloss {
        CanCreateGloss::setUp as setUpGlosses;
    } // ; <-- remedies Visual Studio Code colouring bug
    
    private $_repository;

    protected function setUp(): void
    {
        parent::setUp();
        $this->setUpGlosses();
        Queue::fake();

        $this->_repository = resolve(DiscussRepository::class);
    }

    public function testGetThreadForEntityShouldBeNull()
    {
        $thread = $this->_repository->getThreadDataForEntity('glossv', 1);
        $this->assertEquals(null, $thread);
    }

    public function testGetThreadForEntityShouldBeNew()
    {
        extract( $this->createGloss(__FUNCTION__) );
        $gloss = $this->getRepository()->saveGloss($word, $sense, $gloss, $translations, $keywords, $details);

        $threadData = $this->_repository->getThreadDataForEntity('glossv', $gloss->latest_gloss_version_id, true);
        $this->assertTrue($threadData instanceof ForumThreadForEntityValue);

        $t = $threadData->getThread();
        $this->assertTrue($t instanceof ForumThread);
        $this->assertEquals('glossv', $t->entity_type);
        $this->assertEquals($gloss->latest_gloss_version_id, $t->entity_id);
        $this->assertEquals(Auth::user()->id, $t->account_id);
        $this->assertEquals(
            ForumGroup::where('role', 'glossv')->first()->id,
            $t->forum_group_id
        );
        $this->assertEquals(
            0,
            $t->id
        );
    }

    public function testGetThreadForEntityShouldBeExisting()
    {
        extract( $this->createGloss(__FUNCTION__) );
        $gloss = $this->getRepository()->saveGloss($word, $sense, $gloss, $translations, $keywords, $details);

        $threadData = $this->_repository->getThreadDataForEntity('glossv', $gloss->latest_gloss_version_id, true);
        $t = $threadData->getThread();
        $t->subject = 'Subject';

        $existingThreadData = $this->_repository->getThreadDataForEntity('glossv', $gloss->latest_gloss_version_id, true);
        $this->assertTrue($existingThreadData instanceof ForumThreadForEntityValue);

        $t = $existingThreadData->getThread();
        $this->assertTrue($t instanceof ForumThread);
        $this->assertEquals('glossv', $t->entity_type);
        $this->assertEquals($gloss->latest_gloss_version_id, $t->entity_id);
        $this->assertEquals(Auth::user()->id, $t->account_id);
        $this->assertEquals(
            ForumGroup::where('role', 'glossv')->first()->id,
            $t->forum_group_id
        );
        $this->assertEquals(
            $threadData->getThread()->id,
            $t->id
        );
    }

    public function testCanSavePost()
    {
        extract( $this->createGloss(__FUNCTION__) );
        $gloss = $this->getRepository()->saveGloss($word, $sense, $gloss, $translations, $keywords, $details);

        $threadData = $this->_repository->getThreadDataForEntity('glossv', $gloss->latest_gloss_version_id, true);
        $t = $threadData->getThread();
        $t->subject = 'Subject';

        $account = Auth::user();

        $data = [
            'content' => 'This is a test post generated by a unit test.'
        ];
        $post = new ForumPost($data);
        $this->_repository->savePost($post, $t, $account);

        $this->assertNotEquals(0, $post->id);
        foreach ($data as $key => $value) {
            $this->assertEquals($value, $post->{$key});
        }
        $this->assertEquals($t->id, $post->forum_thread_id);
        $this->assertEquals($t->number_of_posts, $t->forum_posts->count());
    }

    public function testCanSaveLikePost()
    {
        $account = Auth::user();
        $post = $this->createPostForUnitTest($account);
        $like = $this->_repository->saveLike($post->id, $account);

        $post->refresh();

        $this->assertTrue($like->id !== 0);
        $this->assertEquals(1, $post->number_of_likes);
        $this->assertEquals(1, $post->forum_thread->number_of_likes);
    }

    public function testCanToggleLikePost()
    {
        $account = Auth::user();
        $post = $this->createPostForUnitTest($account);

        $like = $this->_repository->saveLike($post->id, $account);
        $this->assertTrue($like instanceof ForumPostLike);

        $like = $this->_repository->saveLike($post->id, $account);
        $this->assertNull($like);

        $post->refresh();

        $this->assertEquals(0, $post->number_of_likes);
        $this->assertEquals(0, $post->forum_thread->number_of_likes);
    }

    public function testCanLikePostCountIgnoresDeletedPosts()
    {
        $account = Auth::user();
        $post = $this->createPostForUnitTest($account);

        $like = $this->_repository->saveLike($post->id, $account);
        $this->assertTrue($like instanceof ForumPostLike);

        $post->refresh();
        
        $this->assertEquals(1, $post->number_of_likes);
        $this->assertEquals(1, $post->forum_thread->number_of_likes);

        $this->_repository->deletePost($post);

        $post->refresh();
        
        $this->assertEquals(1, $post->is_deleted);
        $this->assertEquals(1, $post->number_of_likes);
        $this->assertEquals(0, $post->forum_thread->number_of_likes);
    }

    private function createPostForUnitTest(Account $account)
    {
        $entity = ForumDiscussion::create([
            'account_id' => $account->id
        ]);

        $threadData = $this->_repository->getThreadDataForEntity($entity, null, true);
        $thread = $threadData->getThread();
        $thread->subject = 'Test';
        $post = new ForumPost([
            'content' => 'This is a test post generated by a unit test.'
        ]);

        $this->_repository->savePost($post, $thread, $account);
        return $post;
    }
}
